Mooshak2/Models/Entities/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mooshak2.Models.Entities
{
    public class Assignment
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public string Title { get; set; }
        public DateTime DueDate { get; set; }
        public DateTime PublishDate { get; set; }

    }
}

Mooshak2/Models/ViewModels/AssignmentViewModel.cs
using Mooshak2.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Mooshak2.Models.ViewModels
{

    public class AssignmentViewModel
    {
        private MooshakDataContext context = new MooshakDataContext();

        public string Title { get; set; }
        public int ID { get; set; }
        public string Course { get; set; }
        public DateTime? DueDate { get; set; }

        public List<AssignmentMilestoneViewModel> Milestones { get; set; }

        public AssignmentViewModel()
        {

        }

        public AssignmentViewModel(Assignment assignment)
        {
            this.ID = assignment.ID;
            this.Title = assignment.Title;
            this.Milestones = assignment.Milestones.Select(a => new AssignmentMilestoneViewModel(a)).ToList();
            Course course = context.Courses.SingleOrDefault(x => x.ID == assignment.CourseID);
            this.Course = course.Name;
            this.DueDate = assignment.DueDate;
        }
    }

    public class TeachersAssignment
    {
        public List<BasicCourseVM> courses { get; set; }
        public TeacherVM teacherInfo { get; set; }
        public TeachersAssignment()
        {

        }
        public TeachersAssignment(Teacher t)
        {
            courses = t.TeachersInCourses.Select(a => a.Course).Select(a => new BasicCourseVM(a)).ToList();
            teacherInfo = new TeacherVM(t);
        }
    }

    public class TeacherVM
    {
        public int id { get; set; }
        public string name { get; set; }
        public TeacherVM(Teacher t)
        {
            this.id = t.Id;
            this.name = t.Name;
        }

    }
}

Mooshak2/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Mooshak2.Services;
using System.Web.Mvc;
using Mooshak2.Models.Entities;
using Mooshak2.Models.ViewModels;
using Mooshak2.DAL;
using Mooshak2.Models;
using System.IO;
using System.IO.Compression;
using System.Diagnostics;
using Microsoft.Owin.Security;

namespace Mooshak2.Controllers
{
    public class AssignmentController : Controller
    {
        private MooshakDataContext context = new MooshakDataContext();
        private AssignmentsService _service = new AssignmentsService();

        // GET: Assignments
        public ActionResult Instructions()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles ="Teachers")]
        public ActionResult CreateNewAssignment(int teacherId)
        {
            TeacherService service = new TeacherService();
            Teacher t = service.GetTeacherById(teacherId);

            TeachersAssignment model = new TeachersAssignment(t);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Teachers")]
        public ActionResult Create()
        {


            //TODO only allow authenticated teachers to create assignment
            string teachersName = AuthenticationManager.User.Identity.Name;  //commenta út til að leyfa fleiri en teacher

            TeacherService service = new TeacherService();

            //int id = 1; //hardcoded dabs
            int id = service.GetTeacherIdByName(teachersName); //commenta út ef nota á hardcoded dabs
            
            Teacher t = service.GetTeacherById(id);
            TeachersAssignment model = new TeachersAssignment(t);
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Teachers")]
        public ActionResult Create(List<HttpPostedFileBase> file, FormCollection collection)
        {
            ///<summary>
            ///Get all the assignment data from the form
            /// </summary>
            var newAssignment = new Assignment();
            ///<summary>
            ///Convert date and time string to a DateTime variable
            /// </summary>
            newAssignment.Title = collection["assignmentName"];
            string datetimeStr = collection["date"].ToString() + " " + collection["time"].ToString();
            DateTime datetime = new DateTime();
            datetime = DateTime.ParseExact(datetimeStr, "yyyy-MM-dd HH:mm", null);
            newAssignment.DueDate = datetime;
            newAssignment.PublishDate = DateTime.Now;
            var pdf = file.ElementAt(0);
            string pdfName = pdf.FileName;
            var ID = Convert.ToInt32(collection["courseSelect"]);
            newAssignment.CourseID = ID;
            CourseService cService = new CourseService();
            var course  = cService.GetCourseByID(ID);
            string courseName = course.name;
            int mNumber = Convert.ToInt32(collection["noOfMilestones"]);
            int count = 1;
            ///<summary>
            ///Add all milestones to the assignment
            /// </summary>
            for (int i=1; i <= mNumber; i++)
            {
                Milestone milestone = new Milestone();
                milestone.Title = collection["mName" + i];
                milestone.Weight = Convert.ToInt32(collection["mWeight" + i]);
                newAssignment.Milestones.Add(milestone);
                ///<summary>
                ///Save the input file
                /// </summary>
                var input = file.ElementAt(count);
                string filename = input.FileName;
                System.IO.Directory.CreateDirectory(Server.MapPath("~/Code/")
                                        + courseName + "//"
                                        + newAssignment.Title + "//"
                                        + milestone.Title);

                string inputPath = (Server.MapPath("~/Code/")
                                            + courseName
                                            + "//" + newAssignment.Title + "//"
                                            + milestone.Title + "//"
                                            + "input.txt");
                input.SaveAs(inputPath);
                count++;
                
                ///<summary>
                ///Save the output file
                /// </summary>
                var output = file.ElementAt(count);
                filename = output.FileName;
                System.IO.Directory.CreateDirectory(Server.MapPath("~/Code/")
                                        + courseName + "//"
                                        + newAssignment.Title + "//"
                                        + milestone.Title);

                string outputPath = (Server.MapPath("~/Code/")
                                            + courseName
                                            + "//" + newAssignment.Title + "//"
                                            + milestone.Title + "//"
                                            + "output.txt");
                output.SaveAs(outputPath);
                count++;

            }
            ///<summary>
            ///Add a message to the user, letting him know that
            ///the operation as been successful
            /// </summary>
            ViewBag.Result = "Successfully created new assignment!";

            ///<summary>
            ///Save the description pdf file
            /// </summary>
            System.IO.Directory.CreateDirectory(Server.MapPath("~/Code/") 
                                        + courseName + "//"
                                        + newAssignment.Title);

            string path = (Server.MapPath("~/Code/") 
                                        + courseName
                                        + "//" + newAssignment.Title + "//"
                                        + newAssignment.Title
                                        +".pdf");
            pdf.SaveAs(path);

            ///<summary>
            ///Add the new assignment entry to the database
            /// </summary>
            context.Assignments.InsertOnSubmit(newAssignment);
            context.SubmitChanges();

            ///<summary>
            ///Create the model to return to the view
            /// </summary>
            string teachersName = AuthenticationManager.User.Identity.Name;  //commenta út til að leyfa fleiri en teacher

            TeacherService service = new TeacherService();
            int id = service.GetTeacherIdByName(teachersName); //commenta út ef nota á hardcoded dabs

            Teacher t = service.GetTeacherById(id);

            TeachersAssignment model = new TeachersAssignment(t);

            return View(model);
        }


        public JsonResult Create(Assignment model)
        {
            AssignmentsService service = new AssignmentsService();
            RequestResponse response = service.CreateAssignment(model);
            return Json(response);
        }
        [Authorize]
        public ActionResult Details(int id)
        {
            var model = _service.GetAssignmentByID(id);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Submit(HttpPostedFileBase file, FormCollection collection)
        {
            ///<summary>
            ///Get info of chosen assignment to navigate a path to save the file
            ///</summary>
            string mTitle = collection["milestoneSelect"];
            var milestone = context.Milestones.FirstOrDefault(x => x.Title == mTitle);
            var assignment = context.Assignments.SingleOrDefault(x => x.ID == milestone.AssignmentID);
            var course = context.Courses.SingleOrDefault(x => x.ID == assignment.CourseID);
            var submission = new DAL.Submission();
            submission.SubmitTime = DateTime.Now;
            string time = DateTime.Now.ToString("yyyy-MM-dd HH.mm.ss");
            submission.MilestoneID = milestone.ID;
            submission.Title = User.Identity.Name;
            submission.UserName_ = User.Identity.Name;
            var username = submission.UserName_;
            var path = "";
            if (file != null && file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                ///<summary>
                ///Create a folder from Assignment/Milestone/User/noOfSubmissions
                ///and save the file there
                ///</summary>
                Directory.CreateDirectory(Server.MapPath("~/Code/")
                                         + course.Name + "\\"
                                         + assignment.Title + "\\"
                                         + milestone.Title + "\\"
                                         + username + "\\"
                                         + time + "\\");

                path = Path.Combine(Server.MapPath("~/Code/")
                                         + course.Name + "\\"
                                         + assignment.Title + "\\"
                                         + milestone.Title + "\\"
                                         + username + "\\"
                                         + time + "\\", fileName);
                file.SaveAs(path);
            }


            ///<summary>
            ///If this is a zip file then we unzip it into the same folder.
            ///</summary>
            string extractPath = Server.MapPath("~/Code/")
                                         + course.Name + "\\"
                                         + assignment.Title + "\\"
                                         + milestone.Title + "\\"
                                         + username + "\\"
                                         + time + "\\";
            if (Path.GetExtension(path) == ".zip")

Mooshak2/Views/Assignment/Create.cshtml
@model Mooshak2.Models.ViewModels.TeachersAssignment
@{
    ViewBag.Title = "Create New Assignment";
}
<a href="~/Assignment/Instructions">Instructions</a>
<div id="assignmentControl">
    <h2>Create new assignment</h2>
    @if (ViewBag.result == "Successfully created new assignment!")
    {
        <div class="alert alert-success" id="success" role="alert">
            <p>@ViewBag.result</p>
        </div>
    }
    @using (Html.BeginForm("Create", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <label for="courseSelect">Your courses</label>
        <select id="courseSelect" name="courseSelect" class="form-control">
            @foreach (var c in Model.courses)
            {
                <option value="@c.Id">@c.name</option>
            }
        </select>
        <label for="assignmentName">Assignment Name </label>
        <input type="text" required class="form-control" id="assignmentName" name="assignmentName" /><br />
        <label for="date">Opening date</label>
        <input type="date"  required class="form-control" /><br />
        <label for="time">Publishing time</label>
        <input type="time" required class="form-control" />
        <label for="date">Closing date</label>
        <input type="date" id="date" name="date" required class="form-control" /><br />
        <label for="time">Closing time</label>
        <input type="time" id="time" name="time" required class="form-control" />
        <label for="pdf">Description(.pdf)</label>
        <input type="file" required name="file" class="form-control" id="pdf" /><br />
                <label for="noOfMilestones">Number of Milestones</label>
                <input type="number" class="form-control" onchange="addMilestones()" id="noOfMilestones" name="noOfMilestones" min="1">
        //<input type="button" class="form-control" onclick="addMilestones()" value="Add milestones">
        <style>
            .milestones {
                position: absolute;
                margin-left: 40%;
                margin-top: -30%;
                width: 50%;
            }
        </style>
        <div class="panel-group milestones" id="accordion">

        </div>


                <input type="submit" id="submit" class="form-control" value="Create Assigment" />
    }
</div>

Mooshak2/Views/Assignment/CreateNewAssignment.cshtml
@model Mooshak2.Models.ViewModels.TeachersAssignment
@{
    ViewBag.Title = "CreateNewAssignment";
}

<h2>CreateNewAssignment</h2>
<select>
    @foreach (var c in Model.courses)
    {

        <option value="@c.Id">@c.name</option>
        
    }
</select>

Mooshak2/Views/Assignment/Details.cshtml
@model Mooshak2.Models.ViewModels.AssignmentViewModel
@{
    ViewBag.Title = "Submit your code";
}
    <div class="page-header">
        <h1> @Model.Title</h1>
        <h2>@Model.DueDate</h2>
    </div>

    <br />
    <br />

    <div class="row">
        <div class="col-md-4">
            @using (Html.BeginForm("Submit", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {   <select class="form-control" id="milestoneSelect" name="milestoneSelect">
            @foreach (var mstone in Model.Milestones)
                {
                <option value="@mstone.Title">@mstone.Title</option>
            }
        </select>
        <br />
        <input type="file" id="file" name="file" accept=".cpp,.zip"
               required="required" />
                <br />
                <label for="file">.zip, .cpp</label>
                <br />
                <input type="Submit" class="btn btn-primary" value="Submit" />
                <br />
                <br />
            }


            @if (ViewBag.Output != null)
            {
                <p>@ViewBag.Output</p>
            }
        </div>

    <br />
    <style>
        .wrong {
            color:red;
        }
    </style>
    <div class="col-md-4">
    </div>
        <table class="table table-striped" id="DetailsTable">
            <thead>
                <tr>
                    <th class="tablehead">Username</th>
                    <th class="tablehead">Problem</th>
                    <th class="tablehead">Result</th>
                    <th class="tablehead">Time</th>
                    <th class="tablehead">Course</th>
                    <th class="tablehead"></th>
                </tr>
            </thead>
            <tbody>
            @foreach(var milestone in Model.Milestones)
            {
                foreach(var submission in milestone.Submissions)
                {
                    <tr>
                        <td>@submission.Title</td>
                        <td>@submission.Milestone</td>
                        @if (submission.Result == "Accepted")
                        {
                            <td style="color:green;"><strong>@submission.Result</strong></td>
                        }
                        else 
                        {
                        <td style="color:red;"><strong>@submission.Result</strong></td>        
                        }
                        <td>@submission.Time</td>
                        <td>@submission.Course</td>
                        <td><button class="btn btn-xs" onclick="submissionResults(@submission.ID)">view</button></td>
                    </tr>
                }
            }
            </tbody>

        </table>

</div>

Mooshak2/Views/Assignment/Instructions.cshtml
@{
    ViewBag.Title = "Instructions";
}
<a href="~/Assignment/Create">Back</a>
<h2>
    Instructions for creating an assignment.
</h2>
<h3>Example: A simple program that takes in 2 numbers and adds them</h3>
<pre>
#include <iostream>
using namespace std;
    int main() {
        int n1, n2;
        cin >> n1;
        cin >> n2;
        cout << n1 << " + " << n2 << " = " << n1+n2;
    }
</pre>
<h3>Input for each test should be in a single line</h3>
<pre>
3 4
4 5
5 6</pre>
<h3>Output should be seperated with "##END##" after each test</h3>

<pre>
3 + 4 = 7
##END##
4 + 5 = 9
##END##
5 + 6 = 11
##END##
</pre>

<h2>Input and output should be in two seperate .txt files</h2>

Mooshak2/Views/Assignment/Results.cshtml
 @model Mooshak2.Models.ViewModels.SubmissionViewModel

@if (Model.UserOutput.Count == 0)
{
    if (Model.Result == "Compile time error ")
    {
        <h1>Compile time error</h1>
        <h2>Your program did not compile correctly. Try compiling your code in Code::Blocks or your IDE of choice before submitting</h2>
    }
    else
    {
        <h1>Runtime error</h1>
        <h2>Your program did not execute within the time limit</h2>
    }
}

else
{
    for (int i = 0; i < Model.Input.Count; i++)
    {
        <h1>Test @(i + 1)</h1>
        <h2>Input:</h2>
        <pre>@Model.Input.ElementAt(i)</pre>
        <h2>Expected output</h2>
        <pre class="output">
        @for (int j = 0; j < Model.Output.ElementAt(i).Count; j++)
        {
            @Model.Output.ElementAt(i).ElementAt(j) <br />
        }
        </pre>
        <h2>User Output</h2>
        <pre >
         @for (int j = 0; j < Model.UserOutput.ElementAt(i).Count; j++)
         {
             if (Model.UserOutput.ElementAt(i).ElementAt(j) == Model.Output.ElementAt(i).ElementAt(j))
             {
               <div style="background:#00910F;">@Model.UserOutput.ElementAt(i).ElementAt(j)</div><br />
             }
             else
             {
               <div style="background:#E15C1A;">@Model.UserOutput.ElementAt(i).ElementAt(j)</div><br />
             }
         }
        </pre>
    }
}

Mooshak2/Views/Assignment/Submit.cshtml
@model Mooshak2.Models.ViewModels.AssignmentViewModel
@{
    ViewBag.Title = "C++ Compile test page";
}

<div class="page-header">
    <h1>@Model.Title</h1>
    <h2>@DateTime.Now</h2>
</div>


<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Submit", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {   <select class="form-control" id="milestoneSelect" name="milestoneSelect">
                @foreach (var mstone in Model.Milestones)
                {
                    <option value="@mstone.Title">@mstone.Title</option>
                }
            </select>
            <input type="file" name="file" required="required" />
            <input type="Submit" class="btn btn-primary" value="Compile Test Code" />
        }

        @if (ViewBag.Output != null)
        {
            <p>@ViewBag.Output</p>
        }
    </div>
    <br />
    <div class="col-md-4">
    </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Problem</th>
                    <th>Result</th>
                    <th>Time</th>
                    <th>Course</th>
                </tr>
            </thead>
            <tbody>
            @foreach(var milestone in Model.Milestones)
            {
                foreach(var submission in milestone.Submissions)
                {
                    <tr>
                        <td>@submission.Milestone</td>
                        <td>@submission.Result</td>
                        <td>@submission.Time</td>
                        <td>@submission.Course</td>
                        <td><button class="btn btn-xs">view</button></td>
                    </tr>
                }
            }
            </tbody>

        </table>
</div>